name: ttsse_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - contourpy=1.3.2
  - cycler=0.12.1
  - fonttools=4.58.5
  - freetype=2.13.3
  - joblib=1.5.1
  - kiwisolver=1.4.8
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.8
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.2
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.3.1
  - openjpeg=2.5.3
  - openssl=3.5.1
  - packaging=25.0
  - pandas=2.3.1
  - pillow=11.3.0
  - pip=25.1.1
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.7.0
  - scipy=1.16.0
  - setuptools=80.9.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tzdata=2025b
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
